function createPlot(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 18-Jul-2016 14:26:59

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'GridLineStyle','--',...
    'FontWeight','bold',...
    'FontSize',20,...
    'FontName','Times New Roman');
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','BoostGapFill','Marker','o','Color',[1 0 0]);
set(plot1(2),'DisplayName','FastGapFill','Marker','square','Color',[0 0 1]);

% Create xlabel
xlabel('Percent of reactions removed');

% Create ylabel
ylabel('Percent of reactions recovered');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.727515348329969 0.550605062817452 0.140912727320834 0.0924092384651549],...
    'FontSize',20);

